Alter grid CanAdd MyObjectBuilder_CubeBlock blocks check
N1Ran/BlockLimiter pull request #117
Opened 2024-10-30 23:16 UTC by OwendB1

Reason for this change is that Quantum hangar spawns a grid in with original authorship in tact. Altered check now loops through the owners of all available blocks in the list and then checks each block against its rightful author's limits.

2024-10-30 23:21 UTC, OwendB1 reviewed
All changes checked and tested

2024-11-02 18:03 UTC, OwendB1 commented
@viktor-ferenczi Could you approve this please?

2024-11-02 21:49 UTC, viktor-ferenczi commented
You can try to add me as a reviewer. I do not have the access rights to approve/merge PRs in this repository.

2024-11-02 21:50 UTC, OwendB1 commented
Thats unfortunate, I also cant

2024-11-02 21:50 UTC, OwendB1 commented
@N1Ran Could you review this ASAP please? :)

2024-12-21 13:47 UTC, OwendB1 commented
@N1Ran PR is still open, need this to fix quantum hangar check functionality!

2024-12-21 14:54 UTC, N1Ran requested changes
PR no longer valid and will need re-submission for review

2024-12-21 16:19 UTC, N1Ran requested changes
Make the commented changes and I can push

2024-12-21 16:19 UTC, N1Ran commented on BlockLimiter/BlockLimiter.cs
remove this from the PR

2024-12-21 16:19 UTC, N1Ran commented on BlockLimiter/BlockLimiter.csproj
remove this from the PR

2024-12-21 16:19 UTC, N1Ran commented on BlockLimiter/Utility/Block.cs
This is fine

2024-12-21 16:19 UTC, N1Ran commented on BlockLimiter/Utility/Grid.cs
This is fine

2024-12-21 16:19 UTC, N1Ran commented on BlockLimiter/manifest.xml
remove from PR

2024-12-21 16:19 UTC, N1Ran commented on Setup (run before opening plugin).bat
remove from PR

2024-12-21 16:48 UTC, N1Ran requested changes

2024-12-21 16:48 UTC, N1Ran commented on Setup (run before opening solution).bat
remove the setup.bat also

2024-12-21 22:25 UTC, OwendB1 commented on Setup (run before opening solution).bat
Haven't had the time, will do tomorrow

2025-01-15 09:31 UTC, OwendB1 reviewed
All changes were made according to what you wanted

2025-10-09 23:00 UTC, merged